AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ' serverless doc class'

  Sample SAM Template for docClass

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  DocClassFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
            #CodeUri: app/
            #Handler: app.lambda_handler
      PackageType: Image
      MemorySize: 256
      Role: arn:aws:iam::709169378429:role/S3LambdaRead
      Environment:
        Variables:
          s3_bucket: jgharrisx-docclass
          model_name: v2
      Events:
        DocClassFunctionApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /docclass
            Method: GET
            RestApiId: !Ref DocClassFunctionApi
    Metadata:
      DockerTag: docclass
      DockerContext: .
      Dockerfile: Dockerfile
  DocClassFunctionApi:
    Type: AWS::Serverless::Api
    Properties: 
      StageName: Prod
      Cors: "'*'"
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DocClassFunction:
    Description: "DocClass Lambda Function ARN"
    Value: !GetAtt DocClassFunction.Arn
  DocClassFunctionIamRole:
    Description: "DocClass Lambda Function ARN"
    Value: !GetAtt DocClassFunction.Arn
                
    
